sudo: false
language: cpp

cache:
  apt: true

addons:
  apt:
    packages:
      - libboost-all-dev
      - libasio-dev

compiler:
  - gcc
  - clang

before_script:
  - cd build
  - cmake ..

script:
  - make
