#!/usr/bin/env bash

if [ "$#" -lt 3 ]; then
    echo "usage: $0 <experiment> <node> <relation> <sadDB_gen opts>"
    ../build/sadDB_gen -h
    exit 1
fi

experiment=$1
node=$2
relation=$3

# create directory
mkdir -p "$experiment"/"$node"

# generate serialized random relation
../build/sadDB_gen \
    -o "$experiment"/"$node"/"$relation".txt \
    "${@:4}"
